export class ConstantValues {
    // colection of constant value used in this app.

    public static readonly LICENSETYPES = ['RAM DIST', 'RAM PROD', 'RAM ANY', 'CYC', 'AIR', 'EHS', 'HAZMAT', 'WASTE', 'PERMIT', 'GAS'];
    public static readonly REPORTYPES = ['AIR', 'WATER', 'WASTE'];
    public static readonly  SITELOCATIONS= [
        'Albany',
        'Albuquerque',
        'Atlanta',
        'Birmingham',
        'Boston',
        'Charlottesville',
        'Chicago',
        'Cincinnati',
        'Cleveland Clinic Foundation',
        'Cleveland University Hospital',
        'Columbia',
        'Dallas',
        'Denver',
        'Detroit',
        'Ft. Lauderdale',
        'Hackensack',
        'Houston',
        'Indianapolis',
        'Irvine',
        'Jacksonville',
        'Kansas City',
        'Knoxville',
        'Kolkata',
        'Las Vegas',
        'Little Rock',
        'Loma Linda',
        'London',
        'Mount Vernon',
        'Los Angeles',
        'Louisville',
        'Minneapolis',
        'Nashville',
        'New Orleans',
        'Nottingham',
        'New York City',
        'Palo Alto',
        'Paris',
        'Philadelphia',
        'Phoenix',
        'Portland',
        'Raleigh/Durham',
        'Sacramento',
        'San Antonio',
        'San Diego',
        'San Francisco',
        'Seattle',
        'South Florida',
        'Spokane',
        'Tampa',
        'Tulsa',
        'Winston-Salem'
    ];
    
}
